name: flaskenv
channels:
  - defaults
dependencies:
  - pip 
  - pip:
    - pandas
    - flask
    - langchain>=0.0.2
    - faiss-cpu
    - sentence-transformers
    - networkx
    - python-dotenv
    - flask[async]
    - pinecone-client 
    - pinecone-text
